sonar.projectKey=com.abinbev.b2b:promotion-consumer
sonar.projectName=promotion-consumer

# Modules inherit properties set at parent level
sonar.sources=consumer/src
sonar.sourceEncoding=UTF-8
sonar.language=java
sonar.java.source=17
sonar.java.binaries=consumer/target/classes
sonar.java.libraries=consumer/target/*.jar
sonar.junit.reportPaths=consumer/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=consumer/target/site/jacoco/jacoco.xml

# Exclude unit tests
sonar.exclusions=consumer/src/test/java/**/*,**/config/*.java,**/domain/**/*.java,**/constant/*.java,**/exception/*.java,**/helper/*.java,**/properties/*.java,**/PromotionConsumerApplication.java
sonar.test.exclusions=consumer/src/test/java/**/*
sonar.cpd.exclusions=**/domain/**,**/classes/**
