# Jmeter
jmeter.users=1
jmeter.rampup=30
jmeter.loopcount=1

protocol=https
server=b2b-services-qa.westeurope.cloudapp.azure.com
port=443
context=/v1/promotion-relay
basic-auth=Basic cmVsYXk6TVVRd3JENVplSEtB
country=BR
