db = db.getSiblingDB("Promotion");

db.getCollection('AQ-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('AR-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('BE-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('BR-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('CA-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('CL-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('CO-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('DE-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('DO-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('EC-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('ES-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('GB-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('HN-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('ID-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('MX-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('NL-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('PA-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('PE-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('PY-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('SV-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('TZ-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('UG-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('UY-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );
db.getCollection('ZA-Promotions').createIndex({ vendorId : 1, vendorPromotionId: 1},{unique: 1} );

db.getCollection('AQ-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('AR-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('BE-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('BR-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('CA-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('CL-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('CO-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('DE-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('DO-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('EC-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('ES-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('GB-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('HN-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('ID-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('MX-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('NL-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('PA-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('PE-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('PY-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('SV-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('TZ-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('UG-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('UY-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );
db.getCollection('ZA-Promotions').createIndex({vendorPromotionId: 1, deleted: 1, startDate: 1, endDate: 1} );

db.getCollection('AQ-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('AR-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('BE-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('BR-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('CA-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('CL-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('CO-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('DE-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('DO-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('EC-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('ES-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('GB-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('HN-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('ID-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('MX-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('NL-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('PA-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('PE-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('PY-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('SV-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('TZ-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('UG-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('UY-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('ZA-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('US-Promotions').createIndex({vendorId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );

db.getCollection('AQ-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('AR-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('BE-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('BR-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('CA-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('CL-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('CO-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('DE-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('DO-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('EC-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('ES-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('GB-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('HN-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('ID-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('MX-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('NL-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('PA-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('PE-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('PY-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('SV-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('TZ-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('UG-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('UY-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('ZA-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );
db.getCollection('US-Promotions').createIndex({promotionPlatformId: 1, endDate: 1, deleted: 1, startDate: 1, promotionType: 1 } );

