sonar.projectKey=com.abinbev.b2b:promotion-relay-service
sonar.projectName=promotion-relay-service

# Modules inherit properties set at parent level
sonar.sources=relay/src
sonar.sourceEncoding=UTF-8
sonar.language=java
sonar.java.source=17
sonar.java.binaries=relay/target/classes
sonar.java.libraries=relay/target/*.jar
sonar.junit.reportPaths=relay/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=relay/target/site/jacoco/jacoco.xml

# Exclude unit tests
sonar.exclusions=relay/src/test/java/**/*,**/aspect/*.java,**/classes/*.java,**/config/*.java,**/domain/*.java,**/exceptions/*.java,**/helpers/*.java,**/interceptors/*.java,**/properties/*.java,**/queue/messages/*.java,**/queue/senders/*.java,**/rest/vo/*.java,**/validators/*.java,**/constants/*.java,**/validators/annotations/*.java,**/PromotionRelayServiceApplication.java
sonar.test.exclusions=relay/src/test/java/**/*
