# Jmeter
jmeter.users=10
jmeter.rampup=30
jmeter.loopcount=1000

protocol=https
server=b2b-services-qa.westeurope.cloudapp.azure.com
port=443
context=/v1/promotion-service
jwt-token-admin=
jwt-token-customer=
country=BR
