apiVersion: bees-platform.com/v1alpha1
kind: APIConfig
metadata:
  name: promotion-service-ms
  display: Promotion Service
spec:
  path: promotion-service-apim
  environments:
    - global
    - dtc
  apiSpec:
    format: "swagger-link-json"
    source: "http://conferenceapi.azurewebsites.net/?format=json"