sonar.projectKey=com.abinbev.b2b:promotion-service
sonar.projectName=promotion-service

# Modules inherit properties set at parent level
sonar.sources=api/src
sonar.sourceEncoding=UTF-8
sonar.language=java
sonar.java.source=17
sonar.java.binaries=api/target/classes
sonar.java.libraries=api/target/*.jar
sonar.junit.reportPaths=api/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=api/target/site/jacoco/jacoco.xml

# Exclude unit tests
sonar.exclusions=api/src/test/java/**/*,**/aspect/*.java,**/domain/model/*.java,**/config/*.java,**/exceptions/*.java,**/controllers/*.java,**/interceptors/*.java,**/properties/*.java**,**/formatters/*.java,**/helpers/*.java,**/rest/vo/*.java,**/rest/parameters/*.java,**/validators/*.java,**/constants/*.java,**/validators/annotations/*.java,**/PromotionServiceApplication.java
sonar.test.exclusions=api/src/test/java/**/*
